"use client";

import { Check } from "lucide-react";

import { cn } from "@/lib/utils";

/** How a bundle was made (SPEC.md section 10.2 manifest `label`). */
export type BundleKind = "Reconstructed replay" | "Design storm";

export interface BundleSummary {
  id: string;
  kind: BundleKind;
  city: string;
  /** The bundle window as copy, e.g. "2 July 2019, 05:40 to 09:40 IST". */
  window: string;
  /** One short line on the card; it must be honest about what is synthetic. */
  note: string;
  /** "7 of 49 cycles baked": why the cycle log has the rows it has. Omitted when unknown. */
  status?: string;
  /** False until `make bundle` has written the bundle folder. */
  available: boolean;
  /** ISO window for the replay store. */
  t0: string;
  t1: string;
  /** Where the clock starts when the bundle is selected. */
  simTime: string;
}

export interface BundleCardProps {
  bundle: BundleSummary;
  selected: boolean;
  onSelect: (bundle: BundleSummary) => void;
  className?: string;
}

/**
 * One replay bundle as a selectable card. A missing bundle stays selectable so the operator can
 * queue it, but says "Generated by make bundle" instead of pretending it is on disk. The card
 * carries one line; the bundle's sources and notes sit behind the page's Details disclosure.
 */
export function BundleCard({ bundle, selected, onSelect, className }: BundleCardProps) {
  return (
    <button
      type="button"
      aria-pressed={selected}
      onClick={() => onSelect(bundle)}
      className={cn(
        "rounded-panel bg-deep text-text flex h-full w-full flex-col gap-1.5 border p-4 text-left",
        "focus-visible:ring-tide outline-none focus-visible:ring-2",
        selected ? "border-tide bg-well" : "border-line hover:bg-well",
        className,
      )}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <p className="num type-small text-text font-medium">{bundle.id}</p>
          <p className="type-micro text-text-2">{bundle.city}</p>
        </div>
        <span className="rounded-chip border-line type-micro text-text-2 inline-flex h-6 shrink-0 items-center gap-1 border px-2.5">
          {selected ? <Check size={12} strokeWidth={1.75} aria-hidden="true" /> : null}
          {bundle.kind}
        </span>
      </div>
      <p className="num type-small text-text-2">{bundle.window}</p>
      <p className="type-micro text-text-3">{bundle.note}</p>
      {bundle.status ? <p className="num type-micro text-text-2">{bundle.status}</p> : null}
      {bundle.available ? null : <p className="type-micro text-text-2">Generated by make bundle</p>}
    </button>
  );
}
