"use client";

import { Check } from "lucide-react";

import { cn } from "@/lib/utils";

/** How a bundle was made (SPEC.md section 10.2 manifest `label`). */
export type BundleKind = "Reconstructed replay" | "Design storm";

export interface BundleSummary {
  id: string;
  kind: BundleKind;
  city: string;
  /** The bundle window as copy, e.g. "2 July 2019, 05:40 to 09:40 IST". */
  window: string;
  /** Source note shown on the card; it must be honest about what is synthetic. */
  note: string;
  /** False until `make bundle` has written the bundle folder. */
  available: boolean;
  /** ISO window for the replay store. */
  t0: string;
  t1: string;
  /** Where the clock starts when the bundle is selected. */
  simTime: string;
}

export interface BundleCardProps {
  bundle: BundleSummary;
  selected: boolean;
  onSelect: (bundle: BundleSummary) => void;
  className?: string;
}

/**
 * One replay bundle as a selectable card. A missing bundle stays selectable so the operator can
 * queue it, but says "Generated by make bundle" instead of pretending it is on disk.
 */
export function BundleCard({ bundle, selected, onSelect, className }: BundleCardProps) {
  return (
    <button
      type="button"
      aria-pressed={selected}
      onClick={() => onSelect(bundle)}
      className={cn(
        "flex w-full flex-col gap-2 rounded-panel border bg-deep p-4 text-left text-text",
        "outline-none focus-visible:ring-2 focus-visible:ring-tide",
        selected ? "border-line-strong bg-well" : "border-line hover:bg-well",
        className,
      )}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <p className="num type-small font-medium text-text">{bundle.id}</p>
          <p className="type-micro text-text-2">{bundle.city}</p>
        </div>
        <span className="inline-flex h-6 shrink-0 items-center gap-1 rounded-chip border border-line px-2.5 type-micro text-text-2">
          {selected ? <Check size={12} strokeWidth={1.75} aria-hidden="true" /> : null}
          {bundle.kind}
        </span>
      </div>
      <p className="num type-small text-text-2">{bundle.window}</p>
      <p className="type-micro text-text-3">{bundle.note}</p>
      {bundle.available ? null : (
        <p className="type-micro text-text-2">Generated by make bundle</p>
      )}
    </button>
  );
}
