"""Contract tests for the replay routes (SPEC.md 12; tasks P2.7, P2.10).

The bundles here are folders with a manifest and empty members: ``GET /v1/replay/bundles``
reports which members are *present*, and ``varuna bundle validate`` is what reads them. That
split is deliberate, so the replay page can say "Generated by make bundle" about a folder that
does not exist yet without loading a Zarr store to find out.

The three ``radar`` preview routes are the exception: they decode Zarr, so the
:func:`radar_bundle` fixture writes the demo bundle's two cubes for real, from the seeded
storm designer, over the same window the manifest declares.
"""

from __future__ import annotations

import json
import time
from collections.abc import Iterator
from datetime import datetime, timedelta
from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from varuna_api.replay import summarize_bundle
from varuna_api.routers.replay import design_storm_blocks, storm_cell_rows
from varuna_api.state import AppState
from varuna_cycle.bus import Bus
from varuna_cycle.registry import RunRegistry
from varuna_replay.bundle import (
    RADAR_VARIABLE,
    TRUTH_VARIABLE,
    BundleLayout,
    load_manifest,
    read_cube_info,
    write_cube,
)
from varuna_replay.domain import StormDomain, step_times_min
from varuna_replay.storm import RadarRender, radar_dbz, rain_field, random_storm
from varuna_schemas.constants import IST
from varuna_schemas.models.bundle import BundleManifest, BundleSource, DesignStorm
from varuna_schemas.models.city import RadarDomain
from varuna_schemas.models.common import BBox
from varuna_schemas.models.replay import ReplayBundleSummary
from varuna_schemas.paths import repo_root

BUNDLE_ID = "MUM-2019-07-02"
DESIGN_ID = "MUM-IDF-25yr"
T0 = datetime(2019, 7, 2, 5, 40, tzinfo=IST)
T1 = datetime(2019, 7, 2, 9, 40, tzinfo=IST)
AOI = BBox(min_lon=72.815, min_lat=18.995, max_lon=72.905, max_lat=19.135)
RADAR = RadarDomain(center_lon=72.86, center_lat=19.065, size_km=60.0, res_m=500.0)
CADENCES = {
    "radar": 10,
    "truth": 5,
    "gauges": 15,
    "tide": 15,
    "traffic": 5,
    "reports": 5,
    "cycle": 5,
}

MEMBERS = (
    "radar/frames.zarr",
    "truth/rain.zarr",
    "gauges.csv",
    "tide.csv",
    "traffic/speeds.parquet",
    "reports.jsonl",
    "ground_truth.geojson",
)


CALIBRATION_BASIS = (
    "Inferred, not measured. No hourly hyetograph exists for any Mumbai station over "
    "05:40-09:40 IST on 2 July 2019, so the window accumulation is scaled from the IMD "
    "Santacruz 24-hour total. TIDE. Illustrative, not measured."
)
DESIGN_STORM_BASIS = (
    "Design storm - synthetic. Built from the drainage-norm design intensity in "
    "services/city/configs/mumbai.yaml. It is NOT derived from a published "
    "intensity-duration-frequency curve: no citable IDF value for Mumbai was obtained."
)


def _design_storm() -> DesignStorm:
    """The Chicago hyetograph a design-storm bundle carries, with its basis text."""
    return DesignStorm(
        intensity_mm_h=50.0,
        intensity_source="services/city/configs/mumbai.yaml design_intensity_mm_h.upgraded",
        duration_min=60,
        step_min=15,
        peak_position_r=0.4,
        shape_b_min=10.0,
        shape_c=0.8,
        total_depth_mm=50.0,
        hyetograph_mm_h=[20.0, 50.0, 80.0, 50.0],
        basis=DESIGN_STORM_BASIS,
    )


def _manifest(bundle_id: str, label: str) -> BundleManifest:
    reconstructed = label == "Reconstructed replay"
    sources = (
        [
            BundleSource(
                name="IMD Santacruz 24-hour total, 2 July 2019",
                url="https://mausam.imd.gov.in/mumbai/mcdata/Highest_Scz_July.gif",
                note="375.2 mm for the 24 hours ending 08:30 IST",
                used_for="Window accumulation target",
            )
        ]
        if reconstructed
        else []
    )
    return BundleManifest(
        id=bundle_id,
        city="mumbai",
        label=label,  # type: ignore[arg-type]
        t0=T0,
        t1=T1,
        cadences=CADENCES,
        radar_domain=RADAR,
        aoi=AOI,
        sources=sources,
        seed=2019,
        synthetic_notes=["Radar frames: storm-designer reconstruction."],
        ground_truth_n=29,
        tide_source="illustrative" if reconstructed else None,
        calibration={"aoi_window_accumulation_mm": 75.0} if reconstructed else {},
        calibration_basis=CALIBRATION_BASIS if reconstructed else None,
        design_storm=None if reconstructed else _design_storm(),
        description="Reconstructed replay of the 2 July 2019 morning.",
    )


def _write_bundle(root: Path, bundle_id: str, label: str, *, complete: bool) -> Path:
    folder = root / bundle_id
    folder.mkdir(parents=True, exist_ok=True)
    manifest = _manifest(bundle_id, label)
    (folder / "manifest.json").write_text(
        manifest.model_dump_json(indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    if complete:
        for member in MEMBERS:
            path = folder / member
            path.parent.mkdir(parents=True, exist_ok=True)
            if member.endswith(".zarr"):
                path.mkdir(exist_ok=True)
            else:
                path.write_text("", encoding="utf-8", newline="\n")
    return folder


@pytest.fixture(autouse=True)
def _open_at_the_window_start(monkeypatch: pytest.MonkeyPatch) -> None:
    """These tests read the clock from the window's start; the 06:40 opening has its own test.

    Autouse, so it is set before the ``state`` fixture reads the settings.
    """
    monkeypatch.setenv("VARUNA_REPLAY_OPEN_AT", "off")


@pytest.fixture
def bundles(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A bundles folder holding one complete-looking bundle and one that is only a manifest."""
    root = tmp_path / "bundles"
    monkeypatch.setenv("VARUNA_BUNDLES_DIR", str(root))
    _write_bundle(root, BUNDLE_ID, "Reconstructed replay", complete=True)
    _write_bundle(root, DESIGN_ID, "Design storm", complete=False)
    return root


@pytest.fixture
def client(app: FastAPI, bundles: Path) -> Iterator[TestClient]:
    """The API with the temporary bundles folder in place before the app starts."""
    with TestClient(app) as test_client:
        yield test_client


PNG_MAGIC = b"\x89PNG\r\n\x1a\n"

RADAR_URL = f"/v1/replay/bundles/{BUNDLE_ID}/radar"


@pytest.fixture
def radar_bundle(bundles: Path) -> BundleLayout:
    """The demo bundle with its two cubes written for real, over the manifest's own window.

    The preview routes decode Zarr, so empty members would only ever prove the 404 path. The
    field is the seeded storm designer's (seed 2019), so the frames are the shape ``make
    bundle`` writes: 25 radar frames every 10 minutes, 49 truth frames every 5.
    """
    layout = BundleLayout(root=bundles / BUNDLE_ID)
    domain = StormDomain.from_radar_domain(RADAR, 32643)
    window_min = (T1 - T0).total_seconds() / 60
    design = random_storm(domain, seed=2019, window_min=window_min, n_cells=2)

    radar_times = step_times_min(0.0, window_min, CADENCES["radar"])
    write_cube(
        layout.radar,
        radar_dbz(rain_field(design, domain, radar_times), domain, RadarRender.from_design(design)),
        variable=RADAR_VARIABLE,
        times_min=radar_times,
        domain=domain,
        t0=T0,
        step_min=CADENCES["radar"],
        units="dBZ",
    )
    truth_times = step_times_min(0.0, window_min, CADENCES["truth"])
    write_cube(
        layout.truth,
        rain_field(design, domain, truth_times),
        variable=TRUTH_VARIABLE,
        times_min=truth_times,
        domain=domain,
        t0=T0,
        step_min=CADENCES["truth"],
        units="mm/h",
    )
    return layout


def test_bundles_lists_what_is_on_disk_with_build_and_bake_status(client: TestClient) -> None:
    rows = client.get("/v1/replay/bundles").json()
    assert [row["id"] for row in rows] == [BUNDLE_ID, DESIGN_ID]  # sorted by id

    demo = next(row for row in rows if row["id"] == BUNDLE_ID)
    assert demo["label"] == "Reconstructed replay"
    assert demo["city"] == "mumbai"
    assert demo["t0"] == T0.isoformat()
    assert demo["t1"] == T1.isoformat()
    assert demo["built"] is True
    assert demo["missing_members"] == []
    assert demo["total_cycles"] == 49  # 4 hours of 5-minute cycles, inclusive
    assert demo["baked"] is False
    assert demo["baked_cycles"] == 0
    assert demo["ground_truth_n"] == 29
    assert demo["sources_n"] == 1

    design = next(row for row in rows if row["id"] == DESIGN_ID)
    assert design["built"] is False
    assert design["missing_members"] == ["radar/frames.zarr", "truth/rain.zarr"]


def test_a_bundle_card_carries_the_basis_its_honesty_labels_promise(client: TestClient) -> None:
    """docs/SIMPLIFICATIONS.md points the reader at basis text on /replay; it ships on the card."""
    rows = client.get("/v1/replay/bundles").json()

    demo = next(row for row in rows if row["id"] == BUNDLE_ID)
    assert demo["calibration_basis"] == CALIBRATION_BASIS
    assert demo["tide_source"] == "illustrative"
    assert demo["design_storm_basis"] is None  # a reconstructed replay carries no design storm
    assert [source["name"] for source in demo["sources"]] == [
        "IMD Santacruz 24-hour total, 2 July 2019"
    ]
    assert demo["sources"][0]["url"].startswith("https://")
    assert len(demo["sources"]) == demo["sources_n"]

    design = next(row for row in rows if row["id"] == DESIGN_ID)
    assert design["design_storm_basis"] == DESIGN_STORM_BASIS
    assert design["calibration_basis"] is None
    assert design["tide_source"] is None
    assert design["sources"] == []


def test_bundles_is_empty_when_none_is_generated(
    app: FastAPI, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("VARUNA_BUNDLES_DIR", str(tmp_path / "nothing-here"))
    with TestClient(app) as client:
        assert client.get("/v1/replay/bundles").json() == []


def test_a_baked_cycle_counts_towards_the_bake_status(
    client: TestClient, baked_run: object, state: AppState
) -> None:
    """``baked_run`` writes one run.json; the bundle it names is the demo bundle."""
    row = next(r for r in client.get("/v1/replay/bundles").json() if r["id"] == BUNDLE_ID)
    assert row["baked_cycles"] == 1
    assert row["baked"] is False


def test_clock_opens_the_configured_bundle_paused_at_t0(client: TestClient) -> None:
    clock = client.get("/v1/replay/clock").json()
    assert clock["bundle_id"] == BUNDLE_ID
    assert clock["sim_time"] == T0.isoformat()
    assert clock["playing"] is False
    assert clock["speed"] == 30
    assert clock["mode"] == "baked"
    assert clock["cycle_index"] == 0
    assert clock["n_cycles"] == 49
    assert clock["progress"] == 0.0


def test_the_demo_bundle_opens_at_its_configured_opening() -> None:
    """The console opens on the 06:40 cycle, so the shared clock does too (ADR-0007)."""
    from types import SimpleNamespace

    from varuna_api.replay import _opening_instant

    clock = SimpleNamespace(t0=T0, t1=T0.replace(hour=9, minute=40))

    def settings(open_at: str | None, bundle: str = BUNDLE_ID) -> SimpleNamespace:
        return SimpleNamespace(varuna_replay_open_at=open_at, varuna_bundle=bundle)

    assert _opening_instant(clock, BUNDLE_ID, settings("06:40")) == T0.replace(hour=6, minute=40)
    # Off, empty, another bundle, a time outside the window or nonsense: open at the start.
    assert _opening_instant(clock, BUNDLE_ID, settings("off")) is None
    assert _opening_instant(clock, BUNDLE_ID, settings(None)) is None
    assert _opening_instant(clock, DESIGN_ID, settings("06:40")) is None
    assert _opening_instant(clock, BUNDLE_ID, settings("11:00")) is None
    assert _opening_instant(clock, BUNDLE_ID, settings("six forty")) is None


def test_play_and_pause_move_the_shared_clock(client: TestClient) -> None:
    played = client.post("/v1/replay/play").json()
    assert played["playing"] is True

    paused = client.post("/v1/replay/pause").json()
    assert paused["playing"] is False
    assert paused["sim_time"] >= T0.isoformat()
    assert client.get("/v1/replay/clock").json()["sim_time"] == paused["sim_time"]


def test_seek_clamps_to_the_window_instead_of_refusing(client: TestClient) -> None:
    inside = (T0 + timedelta(minutes=60)).isoformat()
    assert client.post("/v1/replay/seek", json={"sim_time": inside}).json()["sim_time"] == inside

    late = client.post("/v1/replay/seek", json={"sim_time": "2019-07-02T23:00:00+05:30"}).json()
    assert late["sim_time"] == T1.isoformat()

    early = client.post("/v1/replay/seek", json={"sim_time": "2019-07-01T00:00:00+05:30"}).json()
    assert early["sim_time"] == T0.isoformat()


def test_speed_accepts_what_the_time_bar_offers_and_explains_what_it_does_not(
    client: TestClient,
) -> None:
    assert client.post("/v1/replay/speed", json={"speed": 60}).json()["speed"] == 60

    res = client.post("/v1/replay/speed", json={"speed": 7})
    assert res.status_code == 422
    error = res.json()["error"]
    assert error["code"] == "invalid_speed"
    assert "1, 10, 30, 60" in error["message"]
    assert client.get("/v1/replay/clock").json()["speed"] == 60


def test_selecting_another_bundle_moves_the_clock_to_its_window(client: TestClient) -> None:
    clock = client.post("/v1/replay/bundle", json={"bundle_id": DESIGN_ID}).json()
    assert clock["bundle_id"] == DESIGN_ID
    assert clock["playing"] is False
    assert client.get("/v1/replay/clock").json()["bundle_id"] == DESIGN_ID


def test_an_unknown_bundle_says_which_make_target_generates_it(client: TestClient) -> None:
    res = client.post("/v1/replay/bundle", json={"bundle_id": "MUM-2020-08-05"})
    assert res.status_code == 404
    error = res.json()["error"]
    assert error["code"] == "bundle_not_found"
    assert "make bundle BUNDLE=MUM-2020-08-05" in error["message"]
    assert BUNDLE_ID in error["message"]  # what is on disk instead

    assert client.get("/v1/replay/clock", params={"bundle": "MUM-2020-08-05"}).status_code == 404


def test_health_reports_the_clock_once_it_is_open(client: TestClient) -> None:
    assert client.get("/healthz").json()["replay"] is None
    client.get("/v1/replay/clock")
    replay = client.get("/healthz").json()["replay"]
    assert replay["bundle_id"] == BUNDLE_ID
    assert replay["t0"] == T0.isoformat()


def test_the_clock_state_reaches_the_console_over_the_websocket(
    client: TestClient, bus: Bus
) -> None:
    with client.websocket_connect("/v1/live") as ws:
        assert ws.receive_json()["topic"] == "hello"
        # The relay task subscribes after the handshake; publishing before it does would be a
        # race the console never runs into (it subscribes once and stays).
        deadline = time.monotonic() + 2
        while bus.subscriber_count == 0 and time.monotonic() < deadline:
            time.sleep(0.01)

        target = (T0 + timedelta(minutes=45)).isoformat()
        client.post("/v1/replay/seek", json={"sim_time": target})

        # The socket also carries heartbeats (every 0.2 s in tests); skip them.
        for _ in range(10):
            event = ws.receive_json()
            if event["topic"] == "replay.clock":
                break
        assert event["topic"] == "replay.clock"
        assert event["payload"]["sim_time"] == target
        assert event["payload"]["bundle_id"] == BUNDLE_ID


def test_the_radar_index_counts_the_frames_the_cube_holds(
    client: TestClient, radar_bundle: BundleLayout
) -> None:
    index = client.get(RADAR_URL).json()
    info = read_cube_info(radar_bundle.radar, RADAR_VARIABLE)

    assert index["bundle_id"] == BUNDLE_ID
    assert index["label"] == "Reconstructed replay"
    assert index["variable"] == RADAR_VARIABLE
    assert index["n_frames"] == info.shape[0]
    assert index["step_min"] == CADENCES["radar"]
    assert index["t0"] == T0.isoformat()
    assert (index["height"], index["width"]) == (info.shape[1], info.shape[2])

    assert len(index["frames"]) == info.shape[0]
    first, last = index["frames"][0], index["frames"][-1]
    assert first == {"index": 0, "ts": T0.isoformat(), "url": f"{RADAR_URL}/0.png"}
    assert last["ts"] == T1.isoformat()  # the cube covers the whole replay window

    aoi = index["aoi_px"]  # the area of interest is a window inside the 60 km radar domain
    assert 0 <= aoi["left"] < aoi["right"] <= index["width"]
    assert 0 <= aoi["top"] < aoi["bottom"] <= index["height"]
    assert (aoi["width"], aoi["height"]) == (
        aoi["right"] - aoi["left"],
        aoi["bottom"] - aoi["top"],
    )

    assert [band["min_mm_h"] for band in index["ramp"]] == [0.5, 2.0, 8.0, 20.0, 40.0, 80.0]
    assert all(band["hex"].startswith("#") and band["label"] for band in index["ramp"])
    assert index["accumulation"]["url"] == f"{RADAR_URL}/accumulation.png"
    assert index["accumulation"]["label"] == "Accumulation over the replay window, in mm"
    assert "mm" in index["accumulation"]["note"]  # says what the shared legend means


def test_a_radar_frame_is_a_png_the_browser_can_cache(
    client: TestClient, radar_bundle: BundleLayout
) -> None:
    first = client.get(f"{RADAR_URL}/3.png")
    assert first.status_code == 200
    assert first.headers["content-type"] == "image/png"
    assert first.content.startswith(PNG_MAGIC)
    assert first.headers["cache-control"] == "public, max-age=3600"

    etag = first.headers["etag"]
    assert etag.startswith('W/"')  # weak: make bundle rewrites the cube, so never immutable
    again = client.get(f"{RADAR_URL}/3.png")
    assert again.headers["etag"] == etag
    assert again.content == first.content  # rendering is deterministic (rule 8)

    cached = client.get(f"{RADAR_URL}/3.png", headers={"If-None-Match": etag})
    assert cached.status_code == 304
    assert cached.content == b""
    assert cached.headers["etag"] == etag


def test_the_accumulation_png_reads_the_truth_cube(
    client: TestClient, radar_bundle: BundleLayout
) -> None:
    res = client.get(f"{RADAR_URL}/accumulation.png")
    assert res.status_code == 200
    assert res.content.startswith(PNG_MAGIC)
    assert res.headers["cache-control"] == "public, max-age=3600"

    etag = res.headers["etag"]
    assert client.get(f"{RADAR_URL}/accumulation.png").headers["etag"] == etag
    assert (
        client.get(f"{RADAR_URL}/accumulation.png", headers={"If-None-Match": etag}).status_code
        == 304
    )


def test_a_frame_past_the_end_says_how_many_the_bundle_has(
    client: TestClient, radar_bundle: BundleLayout
) -> None:
    res = client.get(f"{RADAR_URL}/999.png")
    assert res.status_code == 404
    error = res.json()["error"]
    assert error["code"] == "frame_not_found"
    assert "25 radar frames" in error["message"]


def test_a_bundle_without_cubes_names_the_member_and_the_make_target(client: TestClient) -> None:
    """``MUM-IDF-25yr`` here is a manifest and nothing else, as a folder is before make bundle."""
    for path in (
        f"/v1/replay/bundles/{DESIGN_ID}/radar",
        f"/v1/replay/bundles/{DESIGN_ID}/radar/0.png",
        f"/v1/replay/bundles/{DESIGN_ID}/radar/accumulation.png",
    ):
        res = client.get(path)
        assert res.status_code == 404, path
        error = res.json()["error"]
        assert error["code"] == "cube_not_built"
        assert f"make bundle BUNDLE={DESIGN_ID}" in error["message"]
    assert ".zarr" in client.get(f"/v1/replay/bundles/{DESIGN_ID}/radar").json()["error"]["message"]


def test_an_unknown_bundle_has_no_radar_preview(client: TestClient) -> None:
    for path in (
        "/v1/replay/bundles/MUM-2020-08-05/radar",
        "/v1/replay/bundles/MUM-2020-08-05/radar/0.png",
        "/v1/replay/bundles/MUM-2020-08-05/radar/accumulation.png",
    ):
        res = client.get(path)
        assert res.status_code == 404, path
        error = res.json()["error"]
        assert error["code"] == "bundle_not_found"
        assert "make bundle BUNDLE=MUM-2020-08-05" in error["message"]


def test_the_preview_does_not_move_the_clock(
    client: TestClient, radar_bundle: BundleLayout
) -> None:
    """Looking at a bundle card is not selecting it: that is POST /v1/replay/bundle."""
    client.post("/v1/replay/bundle", json={"bundle_id": DESIGN_ID})
    assert client.get(RADAR_URL).status_code == 200
    assert client.get("/v1/replay/clock").json()["bundle_id"] == DESIGN_ID


def test_openapi_documents_the_replay_routes(client: TestClient) -> None:
    paths = client.get("/openapi.json").json()["paths"]
    for path in (
        "/v1/replay/bundles",
        "/v1/replay/clock",
        "/v1/replay/play",
        "/v1/replay/pause",
        "/v1/replay/seek",
        "/v1/replay/speed",
        "/v1/replay/bundle",
        "/v1/replay/bundles/{bundle_id}/radar",
        "/v1/replay/bundles/{bundle_id}/radar/{index}.png",
        "/v1/replay/bundles/{bundle_id}/radar/accumulation.png",
    ):
        assert path in paths, path
    assert "501" not in paths["/v1/replay/clock"]["get"]["responses"]
    assert "404" in paths["/v1/replay/clock"]["get"]["responses"]


def test_the_manifest_on_disk_is_the_one_the_api_reports(client: TestClient, bundles: Path) -> None:
    on_disk = json.loads((bundles / BUNDLE_ID / "manifest.json").read_text(encoding="utf-8"))
    row = next(r for r in client.get("/v1/replay/bundles").json() if r["id"] == BUNDLE_ID)
    assert row["seed"] == on_disk["seed"]
    assert row["synthetic_notes"] == on_disk["synthetic_notes"]
    assert row["description"] == on_disk["description"]


def _shipped_card(bundle_id: str, registry: RunRegistry) -> ReplayBundleSummary:
    """One card built from the manifest committed under ``bundles/``, not from a fixture."""
    layout = BundleLayout.for_bundle(repo_root() / "bundles" / bundle_id)
    return summarize_bundle(load_manifest(layout.root), layout, registry)


def test_the_shipped_demo_bundle_states_what_was_inferred_and_what_the_tide_is(
    registry: RunRegistry,
) -> None:
    """The curated MUM-2019-07-02 manifest, through the summary builder the route uses."""
    card = _shipped_card(BUNDLE_ID, registry)

    assert card.calibration_basis is not None
    basis = card.calibration_basis.lower()
    assert "inferred" in basis  # the window accumulation is an inference, never a gauge reading
    assert card.tide_source == "illustrative"
    assert len(card.sources) == 9
    assert card.sources_n == 9
    assert all(source.url.startswith("http") for source in card.sources)


def test_the_shipped_design_storm_says_it_is_not_a_fitted_idf_curve(
    registry: RunRegistry,
) -> None:
    card = _shipped_card(DESIGN_ID, registry)

    assert card.design_storm_basis is not None
    basis = card.design_storm_basis.lower()
    assert "not derived from a published intensity-duration-frequency curve" in basis
    assert "a name, not a fitted return period" in basis
    assert card.calibration_basis is None  # a design storm calibrates against nothing


def _shipped_manifest(bundle_id: str) -> BundleManifest:
    """The manifest committed under ``bundles/``, not the fixture's."""
    return load_manifest(repo_root() / "bundles" / bundle_id)


def test_the_shipped_demo_storm_reaches_the_cell_table_in_the_units_it_prints() -> None:
    """The eight cells of MUM-2019-07-02, converted the way the ``/replay`` table shows them."""
    manifest = _shipped_manifest(BUNDLE_ID)
    assert manifest.storm is not None
    rows = storm_cell_rows(manifest)

    assert len(rows) == 8
    assert [row.id for row in rows] == [cell.id for cell in manifest.storm.cells]
    assert design_storm_blocks(manifest) is None  # a reconstruction has no hyetograph

    first = rows[0]
    cell = manifest.storm.cells[0]
    assert first.birth == manifest.t0 + timedelta(minutes=cell.birth_min)
    assert first.birth.utcoffset() == timedelta(hours=5, minutes=30)
    assert first.sigma_km == pytest.approx(cell.sigma_m / 1000.0)
    assert first.velocity_ms == pytest.approx(manifest.storm.wind_speed_ms, abs=1e-3)
    aoi = manifest.aoi  # cells are born upwind of the city and advect across it
    assert first.start_lat < aoi.max_lat
    assert first.start_lon < aoi.max_lon

    # The manifest keeps the unscaled draw; the field carries intensity_scale times it, and the
    # calibration block states the range of the scaled peaks (rule 6).
    peaks = [row.peak_mm_h for row in rows]
    assert min(peaks) == pytest.approx(manifest.calibration["cell_peak_min_mm_h"], abs=1e-3)
    assert max(peaks) == pytest.approx(manifest.calibration["cell_peak_max_mm_h"], abs=1e-3)
    assert max(peaks) < max(cell.peak_mm_h for cell in manifest.storm.cells)


def test_the_shipped_design_storm_offers_its_hyetograph_instead_of_cells() -> None:
    """A design storm has no cells, so the table gives way to the block sparkline."""
    manifest = _shipped_manifest(DESIGN_ID)
    assert manifest.design_storm is not None
    assert storm_cell_rows(manifest) == []

    blocks = design_storm_blocks(manifest)
    assert blocks is not None
    assert blocks.step_min == 5
    assert len(blocks.blocks_mm_h) == 36  # 180 minutes in 5-minute blocks
    assert blocks.total_depth_mm == pytest.approx(150.0)
    assert blocks.peak_position_r == 0.4

    # The peak sits 40 % into the 180 minutes, in the block that contains minute 72.
    duration_min = blocks.step_min * len(blocks.blocks_mm_h)
    peak = blocks.blocks_mm_h.index(max(blocks.blocks_mm_h))
    assert peak == int(blocks.peak_position_r * duration_min // blocks.step_min)
    assert len(set(blocks.blocks_mm_h)) > 1  # never a uniform block of rain


def test_the_radar_index_carries_the_storm_the_frames_were_generated_from(
    client: TestClient, radar_bundle: BundleLayout
) -> None:
    """Both storm fields are on the index; this fixture's manifest declares neither."""
    index = client.get(RADAR_URL).json()
    assert index["cells"] == []
    assert index["design_storm"] is None
