"""All VARUNA data-contract models.

Import from here (``from varuna_schemas.models import RunMeta``) or from the submodule.
:data:`MODEL_REGISTRY` lists every model in a stable order for the JSON-schema export and
the round-trip tests.
"""

from __future__ import annotations

from varuna_schemas.models.alert import (
    Alert,
    AlertChannel,
    AlertScope,
    AlertState,
    AlertStateChange,
    CapStatus,
    EscalationTarget,
)
from varuna_schemas.models.api import (
    ErrorDetail,
    ErrorEnvelope,
    HealthState,
    HealthStatus,
    LiveEvent,
    RunList,
    RunSummary,
)
from varuna_schemas.models.bundle import (
    BundleLabel,
    BundleManifest,
    BundleSource,
    DesignStorm,
    GroundTruthKind,
    GroundTruthPin,
    StageDatum,
    StormCellSpec,
    StormDesign,
    TideDatum,
    TideSourceKind,
)
from varuna_schemas.models.city import (
    DEFAULT_MANNING_N,
    CityConfig,
    DesignIntensity,
    NestSpec,
    RadarDomain,
    TidalOutfall,
    Tier,
)
from varuna_schemas.models.common import (
    BBox,
    Beta,
    Feature,
    FeatureCollection,
    Geometry,
    HttpUrlStr,
    IdStr,
    Kappa,
    Latitude,
    LineString,
    Longitude,
    LonLat,
    MultiLineString,
    MultiPolygon,
    Point,
    Polygon,
    Position,
    Probability,
    Timestamp,
    VarunaModel,
    to_ist,
)
from varuna_schemas.models.cycle import (
    ComputeRequest,
    CycleLogEntry,
    CycleStageEvent,
    CycleStatus,
    StageStatus,
)
from varuna_schemas.models.drain import (
    Boundary,
    BoundaryType,
    DrainConfidence,
    DrainEdge,
    DrainEdgeHealth,
    DrainHealthProduct,
    DrainNode,
    DrainNodeType,
    DrainShape,
)
from varuna_schemas.models.forecast import (
    NodeForecastRow,
    SafeUntilEntry,
    SegmentForecastRow,
    SegmentSeries,
    SeriesPoint,
)
from varuna_schemas.models.hotspot import (
    AttributionItem,
    CleanTopNEffect,
    FacilityKind,
    Hotspot,
    HotspotExposure,
    HotspotList,
)
from varuna_schemas.models.layers import (
    Asset,
    AssetKind,
    RoadClass,
    RoadSegment,
    SurfaceUnit,
)
from varuna_schemas.models.observation import (
    Observation,
    ObservationEffect,
    ObservationQuality,
    ObservationType,
    ReportAck,
    ReportIn,
)
from varuna_schemas.models.pump import (
    HotspotPumpBenefit,
    Pump,
    PumpAssignment,
    PumpPlan,
    PumpSolver,
    PumpStatus,
)
from varuna_schemas.models.replay import (
    ReplayBundleSummary,
    ReplayClock,
    ReplaySeekRequest,
    ReplaySpeedRequest,
)
from varuna_schemas.models.route import (
    AvoidedSegment,
    Corridor,
    Isochrone,
    ReachabilityResponse,
    ReachMinutes,
    RoadCondition,
    RoadStatus,
    RouteConfidence,
    RouteLabel,
    RouteReason,
    RouteRequest,
    RouteResponse,
    RouteResult,
)
from varuna_schemas.models.run import (
    EngineVersions,
    GridSpec,
    ReplayMode,
    RunIdError,
    RunIdParts,
    RunMeta,
    RunMode,
    build_run_id,
    city_code,
    is_run_id,
    parse_run_id,
    stage_total_ms,
    top_level_stage_ms,
)
from varuna_schemas.models.verification import (
    ContingencyTable,
    FlashLiteScore,
    HotspotScore,
    MissedPin,
    ReliabilityBin,
    SkillByLead,
    VerificationSummary,
)
from varuna_schemas.models.whatif import (
    DeltaClass,
    HotspotDelta,
    PhysicsCheckHotspot,
    PhysicsCheckRequest,
    PhysicsCheckResponse,
    SegmentDelta,
    WhatIfRequest,
    WhatIfResponse,
)

_MODELS: tuple[type[VarunaModel], ...] = (
    # common / GeoJSON
    BBox,
    Point,
    LineString,
    MultiLineString,
    Polygon,
    MultiPolygon,
    Feature,
    FeatureCollection,
    # run
    EngineVersions,
    GridSpec,
    RunMeta,
    # forecast
    SegmentForecastRow,
    NodeForecastRow,
    SeriesPoint,
    SafeUntilEntry,
    SegmentSeries,
    # observation
    ObservationEffect,
    Observation,
    ReportIn,
    ReportAck,
    # alert
    AlertStateChange,
    Alert,
    # pump
    Pump,
    PumpAssignment,
    HotspotPumpBenefit,
    PumpPlan,
    # hotspot
    HotspotExposure,
    AttributionItem,
    CleanTopNEffect,
    Hotspot,
    HotspotList,
    # drain
    DrainNode,
    DrainEdge,
    Boundary,
    DrainEdgeHealth,
    DrainHealthProduct,
    # static layers
    RoadSegment,
    SurfaceUnit,
    Asset,
    # city
    RadarDomain,
    NestSpec,
    DesignIntensity,
    TidalOutfall,
    CityConfig,
    # bundle
    BundleSource,
    StormCellSpec,
    StormDesign,
    DesignStorm,
    BundleManifest,
    GroundTruthPin,
    # replay
    ReplayClock,
    ReplaySeekRequest,
    ReplaySpeedRequest,
    ReplayBundleSummary,
    # cycle
    CycleStatus,
    CycleStageEvent,
    CycleLogEntry,
    ComputeRequest,
    # route
    RouteRequest,
    AvoidedSegment,
    RouteResult,
    Corridor,
    RouteReason,
    RouteResponse,
    Isochrone,
    ReachabilityResponse,
    RoadCondition,
    # what-if
    WhatIfRequest,
    HotspotDelta,
    SegmentDelta,
    WhatIfResponse,
    PhysicsCheckRequest,
    PhysicsCheckHotspot,
    PhysicsCheckResponse,
    # verification
    ContingencyTable,
    HotspotScore,
    SkillByLead,
    ReliabilityBin,
    MissedPin,
    FlashLiteScore,
    VerificationSummary,
    # api
    ErrorDetail,
    ErrorEnvelope,
    LiveEvent,
    HealthStatus,
    RunSummary,
    RunList,
)

MODEL_REGISTRY: dict[str, type[VarunaModel]] = {model.__name__: model for model in _MODELS}
"""Every exported model by class name, in a stable order (used by ``export_json`` and tests)."""

__all__ = [
    "DEFAULT_MANNING_N",
    "MODEL_REGISTRY",
    "Alert",
    "AlertChannel",
    "AlertScope",
    "AlertState",
    "AlertStateChange",
    "Asset",
    "AssetKind",
    "AttributionItem",
    "AvoidedSegment",
    "BBox",
    "Beta",
    "Boundary",
    "BoundaryType",
    "BundleLabel",
    "BundleManifest",
    "BundleSource",
    "CapStatus",
    "CityConfig",
    "CleanTopNEffect",
    "ComputeRequest",
    "ContingencyTable",
    "CycleLogEntry",
    "CycleStageEvent",
    "CycleStatus",
    "DeltaClass",
    "DesignIntensity",
    "DesignStorm",
    "DrainConfidence",
    "DrainEdge",
    "DrainEdgeHealth",
    "DrainHealthProduct",
    "DrainNode",
    "DrainNodeType",
    "DrainShape",
    "EngineVersions",
    "ErrorDetail",
    "ErrorEnvelope",
    "EscalationTarget",
    "FacilityKind",
    "Feature",
    "FeatureCollection",
    "FlashLiteScore",
    "Geometry",
    "GridSpec",
    "GroundTruthKind",
    "GroundTruthPin",
    "HealthState",
    "HealthStatus",
    "Hotspot",
    "HotspotDelta",
    "HotspotExposure",
    "HotspotList",
    "HotspotPumpBenefit",
    "HotspotScore",
    "HttpUrlStr",
    "IdStr",
    "Isochrone",
    "Kappa",
    "Latitude",
    "LineString",
    "LiveEvent",
    "LonLat",
    "Longitude",
    "MissedPin",
    "MultiLineString",
    "MultiPolygon",
    "NestSpec",
    "NodeForecastRow",
    "Observation",
    "ObservationEffect",
    "ObservationQuality",
    "ObservationType",
    "PhysicsCheckHotspot",
    "PhysicsCheckRequest",
    "PhysicsCheckResponse",
    "Point",
    "Polygon",
    "Position",
    "Probability",
    "Pump",
    "PumpAssignment",
    "PumpPlan",
    "PumpSolver",
    "PumpStatus",
    "RadarDomain",
    "ReachMinutes",
    "ReachabilityResponse",
    "ReliabilityBin",
    "ReplayBundleSummary",
    "ReplayClock",
    "ReplayMode",
    "ReplaySeekRequest",
    "ReplaySpeedRequest",
    "ReportAck",
    "ReportIn",
    "RoadClass",
    "RoadCondition",
    "RoadSegment",
    "RoadStatus",
    "RouteConfidence",
    "RouteLabel",
    "RouteRequest",
    "RouteResponse",
    "RouteResult",
    "RunIdError",
    "RunIdParts",
    "RunList",
    "RunMeta",
    "RunMode",
    "RunSummary",
    "SafeUntilEntry",
    "SegmentDelta",
    "SegmentForecastRow",
    "SegmentSeries",
    "SeriesPoint",
    "SkillByLead",
    "StageDatum",
    "StageStatus",
    "StormCellSpec",
    "StormDesign",
    "SurfaceUnit",
    "TidalOutfall",
    "TideDatum",
    "TideSourceKind",
    "Tier",
    "Timestamp",
    "VarunaModel",
    "VerificationSummary",
    "WhatIfRequest",
    "WhatIfResponse",
    "build_run_id",
    "city_code",
    "is_run_id",
    "parse_run_id",
    "stage_total_ms",
    "to_ist",
    "top_level_stage_ms",
]
