/**
 * Replay bundles and the shared clock (SPEC.md sections 7.8 and 12).
 *
 * The API owns the clock: the console does not run a timer of its own. `useReplayClock` reads
 * `GET /v1/replay/clock` once and then follows `replay.clock` events over the socket, writing
 * every update into the replay store, so the time bar, the replay panel and the mode banner
 * all read one state. `useReplayControls` turns a click into the matching POST and adopts the
 * clock the API answers with.
 *
 * When no bundle is generated the clock endpoint answers 404 with the make target to run. That
 * is not an error to hide: `apiReady` goes false, the panel shows its empty state, and the
 * controls fall back to moving the local store so an operator can still scrub the shell.
 */
"use client";

import { useCallback, useEffect, useMemo } from "react";
import { useMutation, useQuery, useQueryClient, type UseQueryOptions } from "@tanstack/react-query";
import { toast } from "sonner";
import { z } from "zod";

import type { CycleLogRow } from "@/components/varuna/cycle-log";
import { useReplayStore, type ReplayMode, type ReplaySpeed } from "@/lib/stores/replay";

import { ApiError, api, apiUrl, errorMessage, timeoutFor } from "./client";
import { useLive } from "./live";
import { queryKeys, shouldRetry } from "./queries";
import { RadarPreview, ReplayBundleList, ReplayClock } from "./schemas";

type QueryOverrides<T> = Omit<UseQueryOptions<T, ApiError>, "queryKey" | "queryFn">;

/** `GET /v1/replay/bundles`: what is under `bundles/`, built or not, baked or not. */
export function useReplayBundles(overrides: QueryOverrides<ReplayBundleList> = {}) {
  return useQuery<ReplayBundleList, ApiError>({
    queryKey: queryKeys.bundles,
    queryFn: () => api.get("/v1/replay/bundles", { schema: ReplayBundleList }),
    staleTime: 30_000,
    refetchOnWindowFocus: false,
    retry: shouldRetry,
    ...overrides,
  });
}

export interface UseRadarPreviewOptions extends Omit<QueryOverrides<RadarPreview>, "enabled"> {
  /** Set false while the bundle's radar cube is missing, so the query never asks for a 404. */
  enabled?: boolean;
}

/**
 * `GET /v1/replay/bundles/{bundle_id}/radar`: the frame index the storm designer animates.
 *
 * A bundle is generated from a seed, so its frames cannot change while the tab is open:
 * `staleTime: Infinity` keeps the index (and the browser cache keeps the PNGs) for the session.
 * A bundle whose cube is not built answers 404, which `shouldRetry` treats as final; pass
 * `enabled: false` for such a bundle so the card shows its "Generated by make bundle" state
 * instead of a failed request.
 */
export function useRadarPreview(
  bundleId: string | undefined,
  options: UseRadarPreviewOptions = {},
) {
  const { enabled = true, ...overrides } = options;
  return useQuery<RadarPreview, ApiError>({
    queryKey: [...queryKeys.bundles, bundleId ?? "", "radar"],
    queryFn: () =>
      api.get(`/v1/replay/bundles/${encodeURIComponent(bundleId ?? "")}/radar`, {
        schema: RadarPreview,
      }),
    enabled: enabled && Boolean(bundleId),
    staleTime: Infinity,
    refetchOnWindowFocus: false,
    retry: shouldRetry,
    ...overrides,
  });
}

/**
 * Absolute URL of one frame's PNG. The index carries API-root-relative paths built by the API
 * itself, so nothing on the page concatenates a route by hand; undefined when the cube has no
 * such frame. The rendering is deterministic, so the browser may cache these for the session.
 */
export function radarFrameUrl(preview: RadarPreview, index: number): string | undefined {
  const frame = preview.frames.find((f) => f.index === index);
  return frame ? apiUrl(frame.url) : undefined;
}

/** Absolute URL of the bundle's accumulation PNG, from the same index. */
export function radarAccumulationUrl(preview: RadarPreview): string {
  return apiUrl(preview.accumulation.url);
}

export interface UseReplayClockOptions extends QueryOverrides<ReplayClock> {
  /** Set false to read the clock without writing it into the replay store. */
  sync?: boolean;
}

/** While the clock has never answered, ask again this often, so a slow start heals by itself. */
export const CLOCK_RECOVER_MS = 15_000;

/**
 * While the clock plays, read it this often as well as following the socket. The socket announces
 * once a simulated minute, and a dropped socket left a playing clock frozen on screen until it
 * reconnected: 06:45 on the page with the API at 06:56 on a loaded laptop (2026-09-29).
 */
export const CLOCK_PLAYING_POLL_MS = 5_000;

/**
 * `GET /v1/replay/clock` plus the `replay.clock` socket events. A missing bundle answers 404,
 * which is a final answer and is not retried.
 *
 * A timeout is not final. The query used to have `retry: false`, so one slow answer from a busy
 * API left every tab on a local clock for the rest of the session: the controls moved only that
 * tab, and the console in the next tab never followed. It retries like every other read now,
 * keeps asking every 15 s until the clock has answered once, and every 5 s while it plays.
 */
export function useReplayClock(options: UseReplayClockOptions = {}) {
  const { sync = true, ...overrides } = options;
  const applyClock = useReplayStore((s) => s.applyClock);
  const queryClient = useQueryClient();

  const query = useQuery<ReplayClock, ApiError>({
    queryKey: queryKeys.replayClock,
    queryFn: () =>
      api.get("/v1/replay/clock", { schema: ReplayClock, timeoutMs: timeoutFor(4_000) }),
    staleTime: 5_000,
    refetchOnWindowFocus: false,
    retry: shouldRetry,
    refetchInterval: (q) =>
      !q.state.data ? CLOCK_RECOVER_MS : q.state.data.playing ? CLOCK_PLAYING_POLL_MS : false,
    ...overrides,
  });

  const { data } = query;
  useEffect(() => {
    if (sync && data) applyClock(data);
  }, [applyClock, data, sync]);

  const onEvent = useCallback(
    (event: { payload?: unknown }) => {
      const parsed = ReplayClock.safeParse(event.payload);
      if (!parsed.success) return;
      queryClient.setQueryData(queryKeys.replayClock, parsed.data);
      if (sync) applyClock(parsed.data);
    },
    [applyClock, queryClient, sync],
  );
  useLive({ topics: ["replay.clock"], onEvent });

  return query;
}

/** One control action, in the shape the API expects it. */
type ReplayCommand =
  | { kind: "play" }
  | { kind: "pause" }
  | { kind: "seek"; simTime: string }
  | { kind: "speed"; speed: ReplaySpeed }
  | { kind: "bundle"; bundleId: string };

function request(command: ReplayCommand): Promise<ReplayClock> {
  const options = { schema: ReplayClock, timeoutMs: timeoutFor(5_000) } as const;
  switch (command.kind) {
    case "play":
      return api.post("/v1/replay/play", {}, options);
    case "pause":
      return api.post("/v1/replay/pause", {}, options);
    case "seek":
      return api.post("/v1/replay/seek", { sim_time: command.simTime }, options);
    case "speed":
      return api.post("/v1/replay/speed", { speed: command.speed }, options);
    case "bundle":
      return api.post("/v1/replay/bundle", { bundle_id: command.bundleId }, options);
  }
}

export interface ReplayControls {
  play: () => void;
  pause: () => void;
  toggle: () => void;
  seek: (simTime: string) => void;
  setSpeed: (speed: ReplaySpeed) => void;
  setMode: (mode: ReplayMode) => void;
  selectBundle: (bundleId: string, window?: { t0: string; t1: string; simTime?: string }) => void;
  /** True when the API has a clock to drive; false while no bundle is generated. */
  apiReady: boolean;
  /** True until the clock has answered or failed for good: reaching it, not missing it. */
  loading: boolean;
  pending: boolean;
  /** Why the clock could not be read, in the API's own words. */
  error: ApiError | null;
  /** Asks the clock again, for the panel's Try again. */
  retry: () => void;
}

/**
 * The replay controls the panel and the time bar share. Every action moves the local store
 * first so the interface answers immediately, then asks the API and adopts its answer; a
 * failure is shown as a toast in the API's own words and the clock is put back where the API
 * last said it was.
 */
export function useReplayControls(): ReplayControls {
  const clock = useReplayClock();
  const store = useReplayStore;
  const applyClock = useReplayStore((s) => s.applyClock);
  const queryClient = useQueryClient();

  const mutation = useMutation<ReplayClock, ApiError, ReplayCommand>({
    mutationFn: request,
    // A clock read already in flight predates this command: landing after it, it would put a
    // paused clock back to playing until the next read.
    onMutate: () => queryClient.cancelQueries({ queryKey: queryKeys.replayClock }),
    onSuccess: (next) => {
      queryClient.setQueryData(queryKeys.replayClock, next);
      applyClock(next);
    },
    onError: (error) => {
      toast.error(errorMessage(error, "The replay clock did not answer. Is the API running?"));
      const last = queryClient.getQueryData<ReplayClock>(queryKeys.replayClock);
      if (last) applyClock(last);
    },
  });

  const apiReady = Boolean(clock.data);
  const { mutate } = mutation;
  const { refetch } = clock;
  const retry = useCallback(() => void refetch(), [refetch]);
  const send = useCallback(
    (command: ReplayCommand) => {
      if (!apiReady) return;
      mutate(command);
    },
    [apiReady, mutate],
  );

  const play = useCallback(() => {
    store.getState().play();
    send({ kind: "play" });
  }, [send, store]);

  const pause = useCallback(() => {
    store.getState().pause();
    send({ kind: "pause" });
  }, [send, store]);

  const toggle = useCallback(() => {
    if (store.getState().playing) pause();
    else play();
  }, [pause, play, store]);

  const seek = useCallback(
    (simTime: string) => {
      store.getState().seek(simTime);
      send({ kind: "seek", simTime: store.getState().simTime });
    },
    [send, store],
  );

  const setSpeed = useCallback(
    (speed: ReplaySpeed) => {
      store.getState().setSpeed(speed);
      send({ kind: "speed", speed });
    },
    [send, store],
  );

  const setMode = useCallback(
    (mode: ReplayMode) => {
      store.getState().setMode(mode);
    },
    [store],
  );

  const selectBundle = useCallback(
    (bundleId: string, window?: { t0: string; t1: string; simTime?: string }) => {
      store.getState().setBundle(bundleId, window);
      send({ kind: "bundle", bundleId });
    },
    [send, store],
  );

  return {
    play,
    pause,
    toggle,
    seek,
    setSpeed,
    setMode,
    selectBundle,
    apiReady,
    loading: !clock.data && !clock.error,
    pending: mutation.isPending,
    error: clock.error ?? null,
    retry,
  };
}

/** One row of `GET /v1/runs`, read loosely: the registry summary has no response model. */
const RegistryRun = z.looseObject({
  run_id: z.string(),
  cycle_ts: z.string(),
  bundle: z.string().nullish(),
  total_ms: z.number().nullish(),
  mass_balance_err: z.number().nullish(),
});

const RegistryRuns = z
  .union([z.array(RegistryRun), z.looseObject({ runs: z.array(RegistryRun) })])
  .transform((value) => (Array.isArray(value) ? value : value.runs));

/**
 * Stages a baked cycle ran. The summary carries the total, not the split, so this names what ran;
 * the split is `GET /v1/runs/{run_id}`'s, drawn in the cycle budget bar.
 */
export const BAKED_STAGES = "sky, twin, flash, pulse, products";

/** The registry's runs as cycle-log rows: one per run, oldest first, ties broken by run id. */
export function toCycleLogRows(
  runs: readonly z.infer<typeof RegistryRun>[],
  bundleId: string | undefined,
): CycleLogRow[] {
  return runs
    .filter((run) => !bundleId || run.bundle === bundleId)
    .map((run) => ({
      id: run.run_id,
      time: run.cycle_ts,
      stages: BAKED_STAGES,
      ms: run.total_ms ?? 0,
      massBalance: run.mass_balance_err ?? null,
    }))
    .sort((a, b) => a.time.localeCompare(b.time) || a.id.localeCompare(b.id));
}

/**
 * The cycle log of one bundle (SPEC.md 7.2, 7.8), from `GET /v1/runs?city=all`: the log follows
 * the *bundle*, and the Chennai design storm is selectable too.
 *
 * A query rather than the bare `fetch` it replaces (`lib/hooks/use-cycle-log.ts`), because that
 * hook had no loading or error state: while the registry was on its way, and after it failed, the
 * log said "No cycles yet. Press Play on the replay." over seven baked cycles.
 */
export function useReplayCycleLog(bundleId: string | undefined) {
  const query = useQuery<z.infer<typeof RegistryRuns>, ApiError>({
    queryKey: [...queryKeys.runs, "cycle-log", "all"],
    queryFn: () => api.get("/v1/runs?city=all&limit=200", { schema: RegistryRuns }),
    staleTime: 30_000,
    refetchOnWindowFocus: false,
    retry: shouldRetry,
  });
  const { data } = query;
  const rows = useMemo(() => (data ? toCycleLogRows(data, bundleId) : []), [data, bundleId]);
  return { ...query, rows };
}
