/**
 * Replay bundles and the shared clock (SPEC.md sections 7.8 and 12).
 *
 * The API owns the clock: the console does not run a timer of its own. `useReplayClock` reads
 * `GET /v1/replay/clock` once and then follows `replay.clock` events over the socket, writing
 * every update into the replay store, so the time bar, the replay panel and the mode banner
 * all read one state. `useReplayControls` turns a click into the matching POST and adopts the
 * clock the API answers with.
 *
 * When no bundle is generated the clock endpoint answers 404 with the make target to run. That
 * is not an error to hide: `apiReady` goes false, the panel shows its empty state, and the
 * controls fall back to moving the local store so an operator can still scrub the shell.
 */
"use client";

import { useCallback, useEffect } from "react";
import { useMutation, useQuery, useQueryClient, type UseQueryOptions } from "@tanstack/react-query";
import { toast } from "sonner";

import {
  useReplayStore,
  type ReplayMode,
  type ReplaySpeed,
} from "@/lib/stores/replay";

import { ApiError, api, apiUrl, errorMessage, timeoutFor } from "./client";
import { useLive } from "./live";
import { queryKeys, shouldRetry } from "./queries";
import { RadarPreview, ReplayBundleList, ReplayClock } from "./schemas";

type QueryOverrides<T> = Omit<UseQueryOptions<T, ApiError>, "queryKey" | "queryFn">;

/** `GET /v1/replay/bundles`: what is under `bundles/`, built or not, baked or not. */
export function useReplayBundles(overrides: QueryOverrides<ReplayBundleList> = {}) {
  return useQuery<ReplayBundleList, ApiError>({
    queryKey: queryKeys.bundles,
    queryFn: () => api.get("/v1/replay/bundles", { schema: ReplayBundleList }),
    staleTime: 30_000,
    refetchOnWindowFocus: false,
    retry: shouldRetry,
    ...overrides,
  });
}

export interface UseRadarPreviewOptions extends Omit<QueryOverrides<RadarPreview>, "enabled"> {
  /** Set false while the bundle's radar cube is missing, so the query never asks for a 404. */
  enabled?: boolean;
}

/**
 * `GET /v1/replay/bundles/{bundle_id}/radar`: the frame index the storm designer animates.
 *
 * A bundle is generated from a seed, so its frames cannot change while the tab is open:
 * `staleTime: Infinity` keeps the index (and the browser cache keeps the PNGs) for the session.
 * A bundle whose cube is not built answers 404, which `shouldRetry` treats as final; pass
 * `enabled: false` for such a bundle so the card shows its "Generated by make bundle" state
 * instead of a failed request.
 */
export function useRadarPreview(
  bundleId: string | undefined,
  options: UseRadarPreviewOptions = {},
) {
  const { enabled = true, ...overrides } = options;
  return useQuery<RadarPreview, ApiError>({
    queryKey: [...queryKeys.bundles, bundleId ?? "", "radar"],
    queryFn: () =>
      api.get(`/v1/replay/bundles/${encodeURIComponent(bundleId ?? "")}/radar`, {
        schema: RadarPreview,
      }),
    enabled: enabled && Boolean(bundleId),
    staleTime: Infinity,
    refetchOnWindowFocus: false,
    retry: shouldRetry,
    ...overrides,
  });
}

/**
 * Absolute URL of one frame's PNG. The index carries API-root-relative paths built by the API
 * itself, so nothing on the page concatenates a route by hand; undefined when the cube has no
 * such frame. The rendering is deterministic, so the browser may cache these for the session.
 */
export function radarFrameUrl(preview: RadarPreview, index: number): string | undefined {
  const frame = preview.frames.find((f) => f.index === index);
  return frame ? apiUrl(frame.url) : undefined;
}

/** Absolute URL of the bundle's accumulation PNG, from the same index. */
export function radarAccumulationUrl(preview: RadarPreview): string {
  return apiUrl(preview.accumulation.url);
}

export interface UseReplayClockOptions extends QueryOverrides<ReplayClock> {
  /** Set false to read the clock without writing it into the replay store. */
  sync?: boolean;
}

/**
 * `GET /v1/replay/clock` plus the `replay.clock` socket events. A missing bundle answers 404,
 * which is a final answer, so this query does not retry.
 */
export function useReplayClock(options: UseReplayClockOptions = {}) {
  const { sync = true, ...overrides } = options;
  const applyClock = useReplayStore((s) => s.applyClock);
  const queryClient = useQueryClient();

  const query = useQuery<ReplayClock, ApiError>({
    queryKey: queryKeys.replayClock,
    queryFn: () => api.get("/v1/replay/clock", { schema: ReplayClock, timeoutMs: timeoutFor(4_000) }),
    staleTime: 5_000,
    refetchOnWindowFocus: false,
    retry: false,
    ...overrides,
  });

  const { data } = query;
  useEffect(() => {
    if (sync && data) applyClock(data);
  }, [applyClock, data, sync]);

  const onEvent = useCallback(
    (event: { payload?: unknown }) => {
      const parsed = ReplayClock.safeParse(event.payload);
      if (!parsed.success) return;
      queryClient.setQueryData(queryKeys.replayClock, parsed.data);
      if (sync) applyClock(parsed.data);
    },
    [applyClock, queryClient, sync],
  );
  useLive({ topics: ["replay.clock"], onEvent });

  return query;
}

/** One control action, in the shape the API expects it. */
type ReplayCommand =
  | { kind: "play" }
  | { kind: "pause" }
  | { kind: "seek"; simTime: string }
  | { kind: "speed"; speed: ReplaySpeed }
  | { kind: "bundle"; bundleId: string };

function request(command: ReplayCommand): Promise<ReplayClock> {
  const options = { schema: ReplayClock, timeoutMs: timeoutFor(5_000) } as const;
  switch (command.kind) {
    case "play":
      return api.post("/v1/replay/play", {}, options);
    case "pause":
      return api.post("/v1/replay/pause", {}, options);
    case "seek":
      return api.post("/v1/replay/seek", { sim_time: command.simTime }, options);
    case "speed":
      return api.post("/v1/replay/speed", { speed: command.speed }, options);
    case "bundle":
      return api.post("/v1/replay/bundle", { bundle_id: command.bundleId }, options);
  }
}

export interface ReplayControls {
  play: () => void;
  pause: () => void;
  toggle: () => void;
  seek: (simTime: string) => void;
  setSpeed: (speed: ReplaySpeed) => void;
  setMode: (mode: ReplayMode) => void;
  selectBundle: (bundleId: string, window?: { t0: string; t1: string; simTime?: string }) => void;
  /** True when the API has a clock to drive; false while no bundle is generated. */
  apiReady: boolean;
  pending: boolean;
  /** Why the clock could not be read, in the API's own words. */
  error: ApiError | null;
}

/**
 * The replay controls the panel and the time bar share. Every action moves the local store
 * first so the interface answers immediately, then asks the API and adopts its answer; a
 * failure is shown as a toast in the API's own words and the clock is put back where the API
 * last said it was.
 */
export function useReplayControls(): ReplayControls {
  const clock = useReplayClock();
  const store = useReplayStore;
  const applyClock = useReplayStore((s) => s.applyClock);
  const queryClient = useQueryClient();

  const mutation = useMutation<ReplayClock, ApiError, ReplayCommand>({
    mutationFn: request,
    onSuccess: (next) => {
      queryClient.setQueryData(queryKeys.replayClock, next);
      applyClock(next);
    },
    onError: (error) => {
      toast.error(errorMessage(error, "The replay clock did not answer. Is the API running?"));
      const last = queryClient.getQueryData<ReplayClock>(queryKeys.replayClock);
      if (last) applyClock(last);
    },
  });

  const apiReady = Boolean(clock.data);
  const { mutate } = mutation;
  const send = useCallback(
    (command: ReplayCommand) => {
      if (!apiReady) return;
      mutate(command);
    },
    [apiReady, mutate],
  );

  const play = useCallback(() => {
    store.getState().play();
    send({ kind: "play" });
  }, [send, store]);

  const pause = useCallback(() => {
    store.getState().pause();
    send({ kind: "pause" });
  }, [send, store]);

  const toggle = useCallback(() => {
    if (store.getState().playing) pause();
    else play();
  }, [pause, play, store]);

  const seek = useCallback(
    (simTime: string) => {
      store.getState().seek(simTime);
      send({ kind: "seek", simTime: store.getState().simTime });
    },
    [send, store],
  );

  const setSpeed = useCallback(
    (speed: ReplaySpeed) => {
      store.getState().setSpeed(speed);
      send({ kind: "speed", speed });
    },
    [send, store],
  );

  const setMode = useCallback(
    (mode: ReplayMode) => {
      store.getState().setMode(mode);
    },
    [store],
  );

  const selectBundle = useCallback(
    (bundleId: string, window?: { t0: string; t1: string; simTime?: string }) => {
      store.getState().setBundle(bundleId, window);
      send({ kind: "bundle", bundleId });
    },
    [send, store],
  );

  return {
    play,
    pause,
    toggle,
    seek,
    setSpeed,
    setMode,
    selectBundle,
    apiReady,
    pending: mutation.isPending,
    error: clock.error ?? null,
  };
}
