import { fireEvent, screen, waitFor, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { ReplayScreen } from "@/app/replay/replay-screen";
import { renderWithProviders, stubFetch } from "@/lib/test-utils";
import { useReplayStore } from "@/lib/stores/replay";

vi.mock("next/navigation", () => ({
  usePathname: () => "/replay",
  useRouter: () => ({ push: vi.fn(), replace: vi.fn(), prefetch: vi.fn() }),
}));

const DEMO = {
  id: "MUM-2019-07-02",
  city: "mumbai",
  label: "Reconstructed replay",
  t0: "2019-07-02T05:40:00+05:30",
  t1: "2019-07-02T09:40:00+05:30",
  seed: 2019,
  built: true,
  missing_members: [],
  baked: false,
  baked_cycles: 0,
  total_cycles: 49,
  sources_n: 3,
  ground_truth_n: 29,
  synthetic_notes: ["Radar frames: storm-designer reconstruction."],
  description: "Reconstructed replay of the 2 July 2019 morning.",
};

const CHENNAI = {
  ...DEMO,
  id: "CHN-IDF-25yr",
  city: "chennai",
  label: "Design storm",
  t0: "2026-11-05T05:40:00+05:30",
  t1: "2026-11-05T08:40:00+05:30",
  built: false,
  missing_members: ["radar/frames.zarr", "truth/rain.zarr"],
  total_cycles: 37,
  ground_truth_n: 0,
  synthetic_notes: ["Design storm: a synthetic scenario, not a recorded event."],
  description: null,
};

const CLOCK = {
  bundle_id: DEMO.id,
  sim_time: DEMO.t0,
  playing: false,
  speed: 30,
  t0: DEMO.t0,
  t1: DEMO.t1,
  cycle_index: 0,
  n_cycles: 49,
  mode: "baked",
  last_run_id: null,
  next_cycle_ts: "2019-07-02T05:45:00+05:30",
  note: null,
  progress: 0,
};

function stub(bundles: unknown[] = [DEMO, CHENNAI]) {
  const fetchMock = vi.fn(
    stubFetch({
      "/v1/replay/bundles": bundles,
      "/v1/replay/clock": CLOCK,
      "/v1/replay/bundle": CLOCK,
    }),
  );
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}

describe("ReplayScreen", () => {
  beforeEach(() => {
    useReplayStore.getState().reset();
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    useReplayStore.getState().reset();
  });

  it("lists the bundles the API reports, not a hard-coded set", async () => {
    stub();
    renderWithProviders(<ReplayScreen />);

    expect(screen.getByRole("heading", { level: 1, name: "Smriti" })).toBeInTheDocument();
    // The Sanskrit name is answered on the page: its English gloss sits under the title (ADR-0085).
    expect(screen.getByRole("heading", { level: 1, name: "Smriti" })).toHaveAccessibleDescription(
      /^Replay/,
    );
    expect(await screen.findByRole("button", { name: /MUM-2019-07-02/ })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /CHN-IDF-25yr/ })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: /MUM-2019-07-02/ })).toHaveTextContent(
      "2 July 2019, 05:40 to 09:40 IST",
    );
  });

  it("labels the header with the selected bundle's kind and names no event of its own", async () => {
    // Section 6.8 and rule 7: the header's first statement about the replay is its honesty label,
    // and the Sanskrit gloss under it neither claims fidelity nor names 2 July 2019, because the
    // same screen plays the design storms.
    stub();
    renderWithProviders(<ReplayScreen />);

    const heading = screen.getByRole("heading", { level: 1, name: "Smriti" });
    expect(heading).not.toHaveAccessibleDescription(/2 July|remembered/);
    const header = heading.parentElement as HTMLElement;
    expect(await within(header).findByText("Reconstructed replay")).toBeInTheDocument();

    // Read straight after the click: the stubbed clock still names the demo bundle, so its next
    // poll points the store back at it.
    fireEvent.click(screen.getByRole("button", { name: /CHN-IDF-25yr/ }));
    expect(within(header).getByText("Design storm")).toBeInTheDocument();
    expect(within(header).queryByText("Reconstructed replay")).not.toBeInTheDocument();
  });

  it("says a bundle is not on disk yet rather than pretending it is", async () => {
    stub();
    renderWithProviders(<ReplayScreen />);

    const chennai = await screen.findByRole("button", { name: /CHN-IDF-25yr/ });
    expect(chennai).toHaveTextContent("Generated by make bundle");
    expect(chennai).toHaveTextContent("Missing radar/frames.zarr, truth/rain.zarr");
    expect(screen.getByRole("button", { name: /MUM-2019-07-02/ })).not.toHaveTextContent(
      "Generated by make bundle",
    );
  });

  it("points the clock at the bundle the operator picks", async () => {
    const fetchMock = stub();
    renderWithProviders(<ReplayScreen />);

    const chennai = await screen.findByRole("button", { name: /CHN-IDF-25yr/ });
    fireEvent.click(chennai);

    expect(useReplayStore.getState().bundleId).toBe("CHN-IDF-25yr");
    expect(useReplayStore.getState().simTime).toBe(CHENNAI.t0);
    expect(chennai).toHaveAttribute("aria-pressed", "true");
    await waitFor(() => {
      const posted = fetchMock.mock.calls.find(([url]) =>
        String(url).endsWith("/v1/replay/bundle"),
      );
      expect(posted).toBeDefined();
      expect(String(posted?.[1]?.body)).toContain("CHN-IDF-25yr");
    });
  });

  it("says which make target generates a bundle when there is none", async () => {
    stub([]);
    renderWithProviders(<ReplayScreen />);

    expect(await screen.findByText("No bundles yet")).toBeInTheDocument();
    expect(
      screen.getByText(
        "Run make bundle BUNDLE=MUM-2019-07-02 to generate the reconstructed replay, then reload.",
      ),
    ).toBeInTheDocument();
  });

  it("holds the cycle log and the storm designer in their empty states", async () => {
    stub();
    renderWithProviders(<ReplayScreen />);

    expect(await screen.findByText("No cycle yet")).toBeInTheDocument();
    expect(screen.getAllByText("No cycles yet").length).toBeGreaterThan(0);
    expect(
      screen.getByText("Editing the storm is coming in pilot; the demo storm is read-only"),
    ).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Generate bundle" })).toBeDisabled();
  });
});
