"""VARUNA's CAP documents against the OASIS CAP 1.2 schema (SPEC.md 7.5 AC2, 11.10, 14).

Section 7.5 asks for a *test* that the CAP XML validates, and section 14 lists "CAP XML
validates" among the correctness gates. Until this file, ``xmlschema`` was a declared dependency
that nothing imported, so the claim rested on the generator looking right.

What is checked, and why each is here:

- the vendored schema is the file that was retrieved (its sha256 matches ``SOURCE.txt``);
- the validator bites: a document missing ``<event>`` or carrying a status CAP does not define
  fails with an error that names the element, so a green run means something;
- CAP generated by :mod:`varuna_products.alerts` validates, from a small fixture, so the check
  runs in CI without baked runs;
- a replay alert says ``Exercise`` and only a live one says ``Actual`` (11.10);
- every committed ``demo/runs/*/alerts/*.cap.xml`` validates and says ``Exercise``, and each one
  is reproduced byte for byte from its run's ``alerts.json`` - so the timestamp fix below changed
  no shipped document (rule 8).

Everything here reads only the vendored schema and passes under ``VARUNA_OFFLINE=1``.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timedelta, timezone
from typing import TYPE_CHECKING, Any
from xml.etree import ElementTree as ET

import pytest
from varuna_products.alerts import CAP_NS, build_alerts, cap_xml
from varuna_products.schemas import CAP_XSD, CAP_XSD_SHA256, validate_cap
from varuna_schemas.paths import repo_root

if TYPE_CHECKING:
    from pathlib import Path

IST = timezone(timedelta(hours=5, minutes=30))
CYCLE = datetime(2019, 7, 2, 6, 40, tzinfo=IST)
N_STEPS = 36

HINDMATA = {
    "hotspot_id": "hindmata",
    "slug": "hindmata",
    "name": "Hindmata junction",
    "ward": "F/S",
    "lon": 72.841,
    "lat": 19.012,
    # Crosses 45 cm for three consecutive steps: a severe alert with a real window.
    "depth_cm": [0.0, 10.0, 20.0, 50.0, 60.0, 55.0, 40.0, 20.0, 10.0] + [0.0] * 27,
}
"""A synthetic depth series at a register name, for generating CAP; not a forecast."""

STREETS = {"Dr Ambedkar Road": [0.0, 16.0, 17.0, 18.0, 0.0] + [0.0] * 31}
"""A street that stays above 15 cm for three steps: a watch alert with no coordinates."""


def _times(cycle: datetime) -> tuple[datetime, ...]:
    return tuple(cycle + timedelta(minutes=5 * (i + 1)) for i in range(N_STEPS))


def _alerts(mode: str, cycle: datetime = CYCLE) -> list[dict[str, Any]]:
    alerts = build_alerts([HINDMATA], "MUM-TEST", cycle, _times(cycle), mode=mode, streets=STREETS)
    assert {a["level"] for a in alerts} == {"severe", "watch"}, "the fixture must raise both"
    return alerts


def _status(xml: str) -> str | None:
    return ET.fromstring(xml).findtext(f"{{{CAP_NS}}}status")


def _demo_cap_files() -> list[Path]:
    return sorted((repo_root() / "demo" / "runs").glob("*/alerts/*.cap.xml"))


# --- the schema itself --------------------------------------------------------------------------


def test_vendored_schema_is_the_retrieved_file() -> None:
    """The XSD on disk hashes to what SOURCE.txt says was retrieved, and the constant agrees."""
    digest = hashlib.sha256(CAP_XSD.read_bytes()).hexdigest()
    recorded = re.search(
        r"^sha256:\s*([0-9a-f]{64})\s*$",
        CAP_XSD.with_name("SOURCE.txt").read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    assert recorded, "SOURCE.txt must carry the sha256 of the vendored schema"
    assert digest == recorded.group(1) == CAP_XSD_SHA256


def test_source_record_names_the_oasis_url_and_date() -> None:
    source = CAP_XSD.with_name("SOURCE.txt").read_text(encoding="utf-8")
    assert "source_url: https://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2.xsd" in source
    assert re.search(r"^retrieved:\s*\d{4}-\d{2}-\d{2}\s*$", source, re.MULTILINE)


# --- the validator bites -------------------------------------------------------------------------


def test_a_document_missing_its_event_fails_naming_the_element() -> None:
    xml = cap_xml(_alerts("baked")[0])
    broken = re.sub(r"\s*<event>Street flooding</event>", "", xml)
    assert broken != xml
    errors = validate_cap(broken)
    assert errors, "a CAP info block without <event> must not validate"
    assert any("event" in error for error in errors), errors


def test_a_status_cap_does_not_define_fails() -> None:
    xml = cap_xml(_alerts("baked")[0]).replace(
        "<status>Exercise</status>", "<status>Replay</status>"
    )
    errors = validate_cap(xml)
    assert errors, "CAP 1.2 defines five statuses and Replay is not one of them"
    assert any(error.startswith("/alert/status:") for error in errors), errors


# --- generated CAP -------------------------------------------------------------------------------


@pytest.mark.parametrize("mode", ["baked", "replay", "live"])
def test_generated_cap_validates(mode: str) -> None:
    for alert in _alerts(mode):
        xml = cap_xml(alert)
        assert validate_cap(xml) == [], xml


@pytest.mark.parametrize("mode", ["baked", "replay"])
def test_replay_alerts_are_exercise(mode: str) -> None:
    """SPEC.md 11.10: a replay must never produce a document mistakable for a live warning."""
    assert {_status(cap_xml(a)) for a in _alerts(mode)} == {"Exercise"}


def test_only_live_alerts_are_actual() -> None:
    assert {_status(cap_xml(a)) for a in _alerts("live")} == {"Actual"}


def test_times_with_microseconds_still_validate() -> None:
    """Regression: ``isoformat()`` wrote ``06:40:00.123456+05:30``, which CAP's pattern rejects."""
    cycle = datetime(2019, 7, 2, 6, 40, 0, 123456, tzinfo=IST)
    for alert in _alerts("baked", cycle):
        xml = cap_xml(alert)
        assert validate_cap(xml) == [], xml
        assert "<sent>2019-07-02T06:40:00+05:30</sent>" in xml


def test_a_time_without_an_offset_is_refused_not_guessed() -> None:
    """A naive time has no offset to write; inventing +05:30 would put an unmeasured time on it."""
    naive = datetime(2019, 7, 2, 6, 40)
    alert = _alerts("baked", naive)[0]
    with pytest.raises(ValueError, match="explicit UTC offset"):
        cap_xml(alert)


# --- the committed demo documents ----------------------------------------------------------------


def test_every_committed_demo_cap_validates_and_is_exercise() -> None:
    files = _demo_cap_files()
    if not files:
        pytest.skip("demo/runs holds no alerts/*.cap.xml in this checkout")
    invalid = {f.name: errors[:2] for f in files if (errors := validate_cap(f))}
    assert not invalid, f"{len(invalid)} of {len(files)} demo CAP files fail CAP 1.2: {invalid}"
    not_exercise = [f.name for f in files if _status(f.read_text(encoding="utf-8")) != "Exercise"]
    assert not not_exercise, f"baked replay CAP must say Exercise: {not_exercise}"


def test_demo_cap_files_are_what_the_generator_writes() -> None:
    """Each committed document is ``cap_xml`` of its own ``alerts.json`` entry, byte for byte.

    This is what makes the validation above a statement about the generator and not only about
    272 files, and it proves the whole-seconds formatting changed no shipped alert (rule 8).
    """
    files = _demo_cap_files()
    if not files:
        pytest.skip("demo/runs holds no alerts/*.cap.xml in this checkout")
    by_run: dict[Path, dict[str, dict[str, Any]]] = {}
    mismatched: list[str] = []
    for path in files:
        run_dir = path.parent.parent
        if run_dir not in by_run:
            payload = json.loads((run_dir / "alerts.json").read_text(encoding="utf-8"))
            by_run[run_dir] = {a["id"]: a for a in payload["alerts"]}
        alert = by_run[run_dir].get(path.name.removesuffix(".cap.xml"))
        if alert is None or cap_xml(alert) != path.read_text(encoding="utf-8"):
            mismatched.append(path.name)
    assert not mismatched, f"{len(mismatched)} of {len(files)} differ: {mismatched[:5]}"
