import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    // The production build the performance pass serves beside `next dev` (P10.4).
    ".next-perf/**",
    ".next-*/**",
    // Diagnostic scripts that prototyped the performance instruments; git-ignored too.
    ".perf-*.mjs",
    // loaders.gl's Draco and Basis workers, copied out of node_modules by
    // `scripts/copy-loader-workers.mjs` (ADR-0069); vendor code, git-ignored, never edited here.
    "public/workers/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `pnpm typegen` (openapi-typescript); never hand-edited.
    "lib/api/types.ts",
    // Playwright artifacts.
    "playwright-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
